/**
* Problem 27: Quadratic Primes
 *
 * Goal: Find the product of the coefficients for the quadratic expression that produces the maximum number of primes for consecutive values of n
 * Difficulty: 1
 */

#include <math.h>
#include <stdbool.h>
#include <stdio.h>
#include "../utils/timer.h"

/**
 * @brief Check if a number is prime
 *
 * Complexity: O(sqrt(n))
 * @return true if prime, false otherwise
 */
bool is_prime (const long long number) {
    if (number <= 1) return false;
    int i = 2;

    bool prime = true;

    while (i <= sqrt(number) && prime) {
        if (number % i == 0) {
            prime = false;
        }
        i++;
    }
    return prime;
}

/**
 * @brief Count consecutive primes generated by n^2 + a*n + b starting at n = 0
 *
 * Complexity: O(k * sqrt(n)) for k consecutive values
 * @return the count of consecutive primes
 */
long long count_consecutive_primes (const long long a, const long long b) {
    long long n = 0;
    while (true) {
        const long long value = n*n + a*n + b;
        if (!is_prime(value)) break;
        n++;
    }
    return n;
}
/**
 * @brief Find coefficients a and b with |a| < 1000 and |b| <= 1000 that maximize consecutive primes
 *
 * Complexity: O(A * B * k * sqrt(n))
 * @return the product a*b
 */
long long solve() {
    long long max_count = 0;
    long long value_a = 0, value_b = 0;

    for (long long b = 2; b <= 1000; b++) {
        if (!is_prime(b)) continue;
        for (long long a = -999; a < 1000; a++) {

            const long long count = count_consecutive_primes(a, b);

            if (max_count < count) {
                max_count = count;
                value_a = a;
                value_b = b;
            }

        }
    }
    return value_a * value_b;
}

/**
 *
 * @brief Main function
 */
int main () {
    start_timer();
    printf("%lld\n", solve());
    stop_timer();
}
