/**
* Problem 29: Distinct Powers
 *
 * Goal: Count how many distinct terms are in the sequence generated by a^b
 *       for 2 <= a <= 100 and 2 <= b <= 100
 *
 * Difficulty: 5%
 *
 */


#include <stdio.h>
#include <stdbool.h>
#include "../utils/timer.h"

/**
 * @brief Compute the sum of all amicable numbers under limit
 *
 * @details Strategy to avoid large number computations:
 *          Instead of computing actual values like 100^100 (too large),
 *          we represent each power in canonical form as (base, exponent)
 *          where base is the smallest prime base.
 *
 * Complexity: O((up_a - low_a) × up_a**1/2 × (up_b - low_b))
 *             The square root comes from factorization up to square root
 *
* @return Number of distinct values in the sequence
 */
long solve(const int low_a, const int up_a, const int low_b, const int up_b) {

    bool seen[101][670] = {false};//log_2(100**100) = 664

    int result = 0;

    for (int a = low_a; a <= up_a; a++) {
        int base = a;
        int k = 1;

        for (int b = low_b; b * b<= a; b++) {
            int temp = a;
            int power = 0;
            while (temp % b == 0) {
                temp /= b;
                power++;
            }
            if (temp == 1) {
                base = b;
                k = power;
                break;
            }
        }

        for (int b = low_b; b <= up_b; b++) {
            const int exp = k * b;
            if (!seen[base][exp]) {
                seen[base][exp] = 1;
                seen[base][exp] = true;
                result++;
            }
        }
    }

    return result;

}

/**
 *@brief Main function
 */
int main() {

    start_timer();
    const long result5 = solve(2,5,2,5);
    printf("Test result = %ld\n", result5);
    stop_timer();

    start_timer();
    const long result = solve(2,100,2,100);
    printf("Result = %ld\n", result);
    stop_timer();
}


